/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

export default function Balloons(props) {
	const mesh3 = useRef();
	const mesh0 = useRef();
	const { nodes, materials } = useGLTF("/models/bday-balloons.glb");
	const viewport = useThree((state) => state.viewport);

	useFrame((state) => {
		const t = state.clock.elapsedTime;
		mesh3.current.position.y = 0.7 + Math.sin(t * 0.2) * 0.1;
		mesh3.current.rotation.y = 0.2 + Math.sin(t * 0.1) * 0.3;
		mesh3.current.rotation.z = 0.2 + Math.sin(t * 0.1) * 0.2;

		mesh0.current.position.y = 0.7 + Math.sin(t * 0.2) * -0.12;
		mesh0.current.rotation.y = -0.27 + Math.sin(t * 0.1) * 0.4;
		mesh0.current.rotation.z = -0.12 + Math.sin(t * 0.1) * 0.4;
	});

	return (
		<group
			{...props}
			dispose={null}
			scale={Math.min(viewport.width / 2, 3.5)}
			position={[0, -1.2, 0]}
		>
			<mesh
				ref={mesh3}
				castShadow
				receiveShadow
				geometry={nodes.balloon_number_three.geometry}
				material={materials.plastic_Mat}
				position={[-0.36, 0.715, 0.1]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				ref={mesh0}
				castShadow
				receiveShadow
				geometry={nodes.balloon_number_zero.geometry}
				material={materials.plastic_Mat}
				position={[0.195, 0.67, -0.033]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/bday-balloons.glb");
