/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Luis 3D (https://sketchfab.com/luism3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cup-of-coffee-with-a-double-wall-glass-5da38330623e41caae7a841c0e6d4e7e
Title: Cup of coffee with a double wall glass
*/
import React, { useRef, useMemo } from "react";
import {
	useGLTF,
	Text,
	MeshTransmissionMaterial,
	MeshDistortMaterial,
	useTexture,
} from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useControls } from "leva";

export default function Model(props) {
	const mesh = useRef();
	const { nodes, materials } = useGLTF("/models/mug.glb");
	const viewport = useThree((state) => state.viewport);
	const textureLoad = useTexture("/textures/coffee.png");

	useFrame(() => {
		mesh.current.rotation.y += 0.003;
	});

	const texture = useMemo(() => {
		const t = textureLoad.clone();
		t.flipY = false;
		t.needsUpdate = true;
		return t;
	}, [textureLoad]);

	const materialProps = useControls("Material", {
		transmission: { value: 1, min: 0, max: 1, step: 0.01 },
		roughness: { value: 0, min: 0, max: 1, step: 0.01 },
		thickness: { value: 0.1, min: 0, max: 2, step: 0.01 },
		ior: { value: 1.1, min: 1, max: 3, step: 0.01 },
		chromaticAberration: { value: 0.1, min: 0, max: 1 },
		backside: true,
	});

	return (
		<group scale={viewport.width / 10}>
			<Text
				fontSize={3}
				font="/fonts/NotoSans-Bold.ttf"
				position={[0, 0, -0.5]}
				fillOpacity={0.5}
			>
				BREW
			</Text>
			<group
				{...props}
				dispose={null}
				position={[0, -1, 0]}
				ref={mesh}
				rotation={[0.5, 0, 0.2]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4.geometry}
					material={materials.Material}
				>
					<MeshTransmissionMaterial {...materialProps} />
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_6.geometry}
					material={materials["Material.001"]}
					position={[0, 1.067, 0]}
					scale={0.99}
				>
					<MeshDistortMaterial distort={0.27} speed={2.8} map={texture} />
				</mesh>
			</group>
		</group>
	);
}

useGLTF.preload("/models/mug.glb");
